### ISSUE TITLE
error in running codes 

### ISSUE THREAD

**Issue by abdelkareemfouda** [akshaybabloo/Emotiv-Matlab#1] opened 2017-04-10 12:38 UTC
>> ExampleUsage
Warning: The data type 'error' used by function EE_EngineConnect does not exist. 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_GetHeadsetSettings' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_SetHeadsetSettings' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_GetSecurityCode' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_CheckSecurityCode' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_GetAverageBandPowers' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_FFTSetWindowingType' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_FFTGetWindowingType' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataCreate' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataFree' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataUpdateHandle' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataGet' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataGetMultiChannels' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataGetNumberOfSample' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataSetBufferSizeInSec' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataGetBufferSizeInSec' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
Warning: The function 'EE_MotionDataGetSamplingRate' was not found in the library 
> In loadlibrary at 403
  In EmotivEEG>EmotivEEG.EmotivEEG at 73
  In ExampleUsage at 2 
EDK library loaded
Successfully connected to Emotiv Systems-5
Successfully disconnected from Emotiv Systems-5
Error using calllib
Method was not found.

Error in EmotivEEG (line 87)
            self.hData = calllib('edk','EE_DataCreate');

Error in ExampleUsage (line 2)
h = EmotivEEG;

**Comment by akshaybabloo** [comment] 2017-04-16 04:22
Could you give me the following details:

1. Matlab version
2. Operating system version
3. Emotiv engine version

**Comment by abdelkareemfouda** [comment] 2017-04-16 13:39
1-windows 7 , 32 bit
2-matlab 2013 a
3- i have purchased pure EEG , and i have the control panel
is that you mean by Emotiv Engine ?

**Comment by fsalsayegh** [comment] 2017-04-23 19:57
I have the same issue and I'm trying to solve it but it doesn't work so please do have the solution ?!!!

**Comment by fsalsayegh** [comment] 2017-04-23 20:00
Error using calllib
Array must be numeric or logical or a pointer to one

Error in EmotivEEG (line 80)
            if calllib('edk','EE_EngineConnect',self.unitIdentifier)

Error in ExampleUsage (line 2)
h = EmotivEEG;


THIS IS THE ERROR

**Comment by abdelkareemfouda** [comment] 2017-04-23 20:11
i have searched too much but i couldn't find a solution

**Comment by akshaybabloo** [comment] 2017-04-24 01:17
I think I know what the problem is. 

The code was written for Emotiv Research SDK v2.0. The current version is a premium version (https://www.emotiv.com/developer/), I am not sure if it's working for the latest release.

Do you have the SDK (premium) installed?

**Comment by fsalsayegh** [comment] 2017-04-24 07:58
hello @akshaybabloo , I have installed the community version not the premium but I will try to install the premium and see if it works .. thank you

**Comment by akshaybabloo** [comment] 2017-04-24 08:21
@fsalsayegh @abdelkareemfouda I think the issue is with the premium version or the SDK version 2.0 (which was released in 2013 or 2014 I guess).

I will close this ticket for now.

**Closed as completed by akshaybabloo** 2017-04-24 08:21 UTC
Labels: question

**Comment by fsalsayegh** [comment] 2017-04-24 09:05
just one more question where can I get the SDK version 2.0 ?

**Comment by fsalsayegh** [comment] 2017-04-24 09:06
just one more question where can I get the SDK version 2.0 ? @akshaybabloo

**Comment by akshaybabloo** [comment] 2017-04-24 11:07
It looks like it's deprecated. https://www.emotiv.com/developer/ -> is the one I think you should look for.
